import Head from "next/head";
import { GetStaticProps } from "next";
import { ConstellationCard } from "../src/card-data";

import Card from '../src/Card'

import styles from '../styles/CardPage.module.css'

export default function AllCards({cards}: {cards: ConstellationCard[]}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>All Cards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {cards.map(card => <Card card={card} />)}
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const cards = await import("../src/card-data")
  return {
    props: {
      cards: cards.cards
    }
  };
};