import Head from "next/head";
import { GetStaticPaths, GetStaticProps } from "next";
import { find, map, pluck, propEq } from "ramda";
import { ConstellationCard } from "../../src/card-data";

import Card from "../../src/Card";

const styles = require("../../styles/CardPage.module.css");

export default function OneCard({ card }: { card: ConstellationCard }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{card.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Card card={card} />
      </main>
    </div>
  );
}

export const getStaticPaths: GetStaticPaths = async (context) => {
    const cards = await import("../../src/card-data");
    const slugs = pluck('slug', cards.cards)
    const paths = map(slug => ({params: {slug}}), slugs)

    return {
        paths,
        fallback: false
    }
}

export const getStaticProps: GetStaticProps = async (context) => {
  const cards = await import("../../src/card-data");
  const slug = context.params['slug']

  const card = find(propEq('slug', slug), cards.cards)
  
  return {
    props: {
      card
    },
    notFound: (card === undefined)
  };
};
